#!/usr/bin/env python3
"""Apply JA/NEI decisions for medium suggestions and optionally sync approved tasks to Notion."""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import re
import sys
from typing import Any

from capture_to_notion import Task, sync_tasks
from scheduled_ingest import DEFAULT_PENDING_SUGGESTIONS_FILE, load_pending_suggestions, save_pending_suggestions


@dataclasses.dataclass
class ParsedDecision:
    action: str  # approve | reject
    run_id: str | None
    all_items: bool
    indices: list[int]
    excluded_indices: list[int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply JA/NEI decision message for pending Notion suggestions.")
    parser.add_argument(
        "--pending-suggestions-file",
        default=DEFAULT_PENDING_SUGGESTIONS_FILE,
        help="Path to suggestion queue file generated by scheduled_ingest.py.",
    )
    parser.add_argument("--decision-text", help="Decision text, e.g. 'JA run-... 1,3' or 'NEI run-... ALLE'.")
    parser.add_argument("--decision-file", help="Optional file containing decision text.")
    parser.add_argument("--run-id", help="Optional run id override. Defaults to run id in decision text or latest.")
    parser.add_argument("--database-id", help="Notion database ID. Defaults to NOTION_DATABASE_ID.")
    parser.add_argument("--token", help="Notion API token. Defaults to NOTION_API_TOKEN.")
    parser.add_argument("--title-property", default="Oppgave")
    parser.add_argument("--status-property", default="Status")
    parser.add_argument("--due-property", default="Frist")
    parser.add_argument("--source-property", default="Source")
    parser.add_argument("--client-project-property", default="Kunde/Prosjekt")
    parser.add_argument("--type-property", default="🏷️ Type")
    parser.add_argument("--priority-property", default="🔥 Prioritet")
    parser.add_argument("--status-value", default="Ikke startet")
    parser.add_argument("--skip-existing", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--confirmation-message-file",
        help="Optional file path to write a Slack-ready confirmation message.",
    )
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()


def read_decision_text(args: argparse.Namespace) -> str:
    if args.decision_text:
        return args.decision_text.strip()
    if args.decision_file:
        with open(args.decision_file, "r", encoding="utf-8") as fh:
            return fh.read().strip()
    if not sys.stdin.isatty():
        data = sys.stdin.read().strip()
        if data:
            return data
    raise SystemExit("Provide decision via --decision-text, --decision-file, or stdin.")


def parse_index_values(fragment: str) -> tuple[bool, list[int]]:
    normalized = fragment.strip().casefold()
    if not normalized:
        return False, []
    all_items = bool(re.search(r"\b(alle|all)\b", normalized))

    values: set[int] = set()
    scrubbed = normalized
    for match in re.finditer(r"\b(\d{1,3})\s*[-–]\s*(\d{1,3})\b", normalized):
        start = int(match.group(1))
        end = int(match.group(2))
        lo = min(start, end)
        hi = max(start, end)
        for number in range(lo, hi + 1):
            values.add(number)
    scrubbed = re.sub(r"\b\d{1,3}\s*[-–]\s*\d{1,3}\b", " ", scrubbed)
    for token in re.findall(r"\b\d{1,3}\b", scrubbed):
        values.add(int(token))
    return all_items, sorted(values)


REJECT_ALIASES = (
    "det stemmer ikke",
    "ikke gjør det",
    "ikke gjor det",
    "ikke legg til",
    "nei",
    "no",
    "avvis",
    "reject",
    "dropp",
    "drop",
    "skip",
    "stopp",
)

APPROVE_ALIASES = (
    "det stemmer",
    "gjør det",
    "gjor det",
    "kjør på",
    "kjor pa",
    "sett i gang",
    "go ahead",
    "godkjenn",
    "approve",
    "legg til",
    "legge til",
    "ja",
    "yes",
    "ok",
    "okei",
    "okey",
    "kjør",
    "kjor",
    "stemmer",
)

SINGULAR_REFERENCE_PATTERNS = (
    r"\bdenne\b",
    r"\bden her\b",
    r"\bden oppgaven\b",
    r"\bthis one\b",
    r"\bakkurat denne\b",
)


def alias_in_text(text: str, alias: str) -> bool:
    pattern = rf"(^|[\s,.:;!?\-]){re.escape(alias)}($|[\s,.:;!?\-])"
    return bool(re.search(pattern, text, flags=re.IGNORECASE))


def detect_action_prefix(text: str) -> tuple[str | None, str]:
    clean = text.strip()
    if not clean:
        return None, clean

    for alias in sorted(REJECT_ALIASES, key=len, reverse=True):
        pattern = rf"^{re.escape(alias)}(?:\b|[\s,:;\-]+)"
        match = re.match(pattern, clean, flags=re.IGNORECASE)
        if match:
            return "reject", clean[match.end() :].strip()
        if clean.casefold() == alias.casefold():
            return "reject", ""

    for alias in sorted(APPROVE_ALIASES, key=len, reverse=True):
        pattern = rf"^{re.escape(alias)}(?:\b|[\s,:;\-]+)"
        match = re.match(pattern, clean, flags=re.IGNORECASE)
        if match:
            return "approve", clean[match.end() :].strip()
        if clean.casefold() == alias.casefold():
            return "approve", ""

    low = clean.casefold()
    if any(alias_in_text(low, alias.casefold()) for alias in REJECT_ALIASES):
        return "reject", clean
    if any(alias_in_text(low, alias.casefold()) for alias in APPROVE_ALIASES):
        return "approve", clean

    return None, clean


def parse_selection_fragment(fragment: str) -> tuple[bool, list[int], list[int]]:
    clean = re.sub(r"\s+", " ", fragment).strip()
    if not clean:
        return False, [], []

    exclude_part = ""
    include_part = clean
    separators = (
        r"\bmen ikke\b",
        r"\bunntatt\b",
        r"\bbortsett fra\b",
        r"\bminus\b",
        r"\butenom\b",
    )
    for separator in separators:
        split = re.split(separator, clean, maxsplit=1, flags=re.IGNORECASE)
        if len(split) == 2:
            include_part, exclude_part = split[0], split[1]
            break

    all_items, include_indices = parse_index_values(include_part)
    _, excluded_indices = parse_index_values(exclude_part)
    return all_items, include_indices, excluded_indices


def parse_decision_text(text: str) -> ParsedDecision:
    clean = re.sub(r"^/[\w-]+\s*", "", text.strip(), flags=re.IGNORECASE)
    clean = re.sub(r"\s+", " ", clean).strip()
    if not clean:
        raise SystemExit("Decision message is empty.")

    run_match = re.search(r"run-[a-z0-9_:+\-\.]+", clean, flags=re.IGNORECASE)
    run_id = run_match.group(0) if run_match else None
    if run_id:
        run_id = run_id.strip("`*_.,;:()[]{}")
    remainder = clean
    if run_id:
        remainder = re.sub(r"run-[a-z0-9_:+\-\.]+", " ", remainder, count=1, flags=re.IGNORECASE)
    remainder = remainder.strip()

    action, remainder = detect_action_prefix(remainder)
    if action is None:
        raise SystemExit(
            "Could not understand decision action. Start with JA/NEI or synonyms like "
            "'gjør det', 'det stemmer', 'dropp', 'ikke gjør det'."
        )

    all_items, indices, excluded_indices = parse_selection_fragment(remainder)
    if not all_items and not indices:
        if any(re.search(pattern, remainder, flags=re.IGNORECASE) for pattern in SINGULAR_REFERENCE_PATTERNS):
            indices = [1]
        else:
            all_items = True
    return ParsedDecision(
        action=action,
        run_id=run_id,
        all_items=all_items,
        indices=indices,
        excluded_indices=excluded_indices,
    )


def select_run(payload: dict[str, Any], run_id: str | None) -> dict[str, Any]:
    runs = payload.get("runs", [])
    if not isinstance(runs, list) or not runs:
        raise SystemExit("No pending suggestion runs found.")

    if run_id:
        for run in runs:
            if isinstance(run, dict) and run.get("run_id") == run_id:
                return run
        raise SystemExit(f"Run id not found: {run_id}")

    for run in runs:
        if isinstance(run, dict) and run.get("status") in {"pending_review", "pending"}:
            return run
    if isinstance(runs[0], dict):
        return runs[0]
    raise SystemExit("Could not resolve a pending run.")


def task_from_entry(entry: dict[str, Any]) -> Task:
    task_data = entry.get("task", {})
    if not isinstance(task_data, dict):
        raise SystemExit("Invalid task payload in suggestion queue.")
    return Task(
        title=str(task_data.get("title", "")),
        due_date=task_data.get("due_date"),
        source_excerpt=str(task_data.get("source_excerpt", "")),
        due_phrase=task_data.get("due_phrase"),
    )


def apply_decision(run: dict[str, Any], decision: ParsedDecision) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    suggestions = run.get("suggestions", [])
    if not isinstance(suggestions, list):
        raise SystemExit("Invalid run format: missing suggestions list.")

    pending_entries = [entry for entry in suggestions if isinstance(entry, dict) and entry.get("status") == "pending"]
    if not pending_entries:
        return [], []

    if decision.all_items:
        selected = pending_entries
    else:
        include_set = set(decision.indices)
        selected = [
            entry
            for entry in pending_entries
            if isinstance(entry.get("index"), int) and entry.get("index") in include_set
        ]
    if decision.excluded_indices:
        exclude_set = set(decision.excluded_indices)
        selected = [
            entry
            for entry in selected
            if not (isinstance(entry.get("index"), int) and entry.get("index") in exclude_set)
        ]

    if not selected:
        return [], []

    approved: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    for entry in selected:
        if decision.action == "approve":
            entry["status"] = "approved"
            approved.append(entry)
        else:
            entry["status"] = "rejected"
            rejected.append(entry)

    unresolved = [entry for entry in suggestions if isinstance(entry, dict) and entry.get("status") == "pending"]
    run["status"] = "resolved" if not unresolved else "partially_resolved"
    return approved, rejected


def build_confirmation_message(
    run_id: str,
    decision: ParsedDecision,
    approved: list[dict[str, Any]],
    rejected: list[dict[str, Any]],
    created: int,
    updated: int,
    skipped: int,
    pending_remaining: int,
    dry_run: bool,
) -> str:
    def noun(count: int) -> str:
        return "denne" if count == 1 else "disse"

    if decision.action == "approve":
        if dry_run:
            return f"Ok, i en test ville jeg lagt til {noun(len(approved))} i Notion-databasen."
        else:
            head = f"Ok, jeg legger {noun(len(approved))} til i Notion-databasen."
            details = f"Opprettet: {created}, oppdatert: {updated}, hoppet over: {skipped}."
            return "\n".join([head, details])
    else:
        return f"Ok, jeg legger ikke til {noun(len(rejected))} i Notion-databasen."


def main() -> None:
    args = parse_args()
    decision_text = read_decision_text(args)
    decision = parse_decision_text(decision_text)

    payload = load_pending_suggestions(args.pending_suggestions_file)
    resolved_run_id = args.run_id or decision.run_id
    run = select_run(payload, resolved_run_id)
    approved, rejected = apply_decision(run, decision)

    created = 0
    updated = 0
    skipped = 0
    if decision.action == "approve" and approved:
        tasks = [task_from_entry(entry) for entry in approved]
        if args.dry_run:
            print(f"Approved tasks (dry-run): {len(tasks)}")
        else:
            sync = sync_tasks(args=args, tasks=tasks, emit_output=False)
            created = sync.created
            updated = sync.updated
            skipped = sync.skipped
            print(
                f"Notion sync from approvals complete. Created: {sync.created}, "
                f"Updated: {sync.updated}, Skipped: {sync.skipped}."
            )

    save_pending_suggestions(args.pending_suggestions_file, payload)

    print(f"Run ID: {run.get('run_id')}")
    print(f"Decision: {decision.action}")
    print(f"Approved: {len(approved)}")
    print(f"Rejected: {len(rejected)}")
    unresolved = [
        entry
        for entry in (run.get("suggestions") if isinstance(run.get("suggestions"), list) else [])
        if isinstance(entry, dict) and entry.get("status") == "pending"
    ]
    print(f"Pending remaining: {len(unresolved)}")

    if args.confirmation_message_file:
        message = build_confirmation_message(
            run_id=str(run.get("run_id") or ""),
            decision=decision,
            approved=approved,
            rejected=rejected,
            created=created,
            updated=updated,
            skipped=skipped,
            pending_remaining=len(unresolved),
            dry_run=args.dry_run,
        )
        directory = os.path.dirname(args.confirmation_message_file)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(args.confirmation_message_file, "w", encoding="utf-8") as fh:
            fh.write(message)


if __name__ == "__main__":
    main()
