#!/usr/bin/env python3
"""Realtime approval listener for Slack thread replies -> Notion suggestions."""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import re
import sys
from typing import Any

from apply_suggestion_decision import (
    apply_decision,
    build_confirmation_message,
    parse_decision_text,
    select_run,
    task_from_entry,
)
from capture_to_notion import sync_tasks
from scheduled_ingest import DEFAULT_PENDING_SUGGESTIONS_FILE, load_pending_suggestions, save_pending_suggestions


DEFAULT_CURSOR_FILE = os.path.join(
    os.path.expanduser("~"),
    ".codex",
    "state",
    "notion-todo-capture",
    "approval_cursor.json",
)
RUN_ID_RE = re.compile(r"\brun-[a-z0-9_:+\-.]+\b", flags=re.IGNORECASE)
APPROVAL_PROMPT_RE = re.compile(
    r"\bskal\s+jeg\s+legge\s+til\s+(?:disse|denne)\s+i\s+notion\b",
    flags=re.IGNORECASE,
)


@dataclasses.dataclass
class ApprovalEvent:
    event_id: str
    text: str
    channel: str | None
    ts: str | None
    thread_ts: str | None
    user: str | None
    thread_root_text: str | None
    is_bot_message: bool


@dataclasses.dataclass
class ListenerResult:
    status: str  # processed | ignored | duplicate | error
    reason: str
    run_id: str | None = None
    approved_count: int = 0
    rejected_count: int = 0
    created: int = 0
    updated: int = 0
    skipped: int = 0
    pending_remaining: int = 0
    confirmation_message: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Process one Slack approval event and apply Notion suggestions.")
    parser.add_argument("--event-file", help="Path to JSON payload (Slack event wrapper or message object).")
    parser.add_argument("--event-json", help="Raw JSON payload as string.")
    parser.add_argument(
        "--pending-suggestions-file",
        default=DEFAULT_PENDING_SUGGESTIONS_FILE,
        help="Path to suggestion queue file generated by scheduled_ingest.py.",
    )
    parser.add_argument(
        "--cursor-file",
        default=DEFAULT_CURSOR_FILE,
        help="Path to processed-event cursor state for idempotency.",
    )
    parser.add_argument("--run-id", help="Optional run id override.")
    parser.add_argument("--database-id", help="Notion database ID. Defaults to NOTION_DATABASE_ID.")
    parser.add_argument("--database-name", default="Oppgaver", help="Database name fallback when database id is absent.")
    parser.add_argument("--token", help="Notion API token. Defaults to NOTION_API_TOKEN.")
    parser.add_argument("--title-property", default="Oppgave")
    parser.add_argument("--status-property", default="Status")
    parser.add_argument("--due-property", default="Frist")
    parser.add_argument("--source-property", default="Source")
    parser.add_argument("--client-project-property", default="Kunde/Prosjekt")
    parser.add_argument("--type-property", default="🏷️ Type")
    parser.add_argument("--priority-property", default="🔥 Prioritet")
    parser.add_argument("--status-value", default="Ikke startet")
    parser.add_argument("--skip-existing", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--confirmation-message-file",
        help="Optional output file for Slack thread confirmation message.",
    )
    parser.add_argument(
        "--result-file",
        help="Optional output JSON file with listener result payload.",
    )
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()


def read_event_payload(args: argparse.Namespace) -> dict[str, Any]:
    if args.event_json:
        return json.loads(args.event_json)
    if args.event_file:
        with open(args.event_file, "r", encoding="utf-8") as fh:
            return json.load(fh)
    if not sys.stdin.isatty():
        raw = sys.stdin.read().strip()
        if raw:
            return json.loads(raw)
    raise SystemExit("Provide event payload via --event-file, --event-json, or stdin.")


def _coerce_str(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def normalize_event(raw_payload: dict[str, Any]) -> ApprovalEvent:
    event = raw_payload.get("event") if isinstance(raw_payload.get("event"), dict) else raw_payload
    if not isinstance(event, dict):
        raise SystemExit("Event payload must be a JSON object or wrapper with an 'event' object.")

    text = _coerce_str(event.get("text")) or ""
    channel = _coerce_str(event.get("channel"))
    ts = _coerce_str(event.get("ts"))
    thread_ts = _coerce_str(event.get("thread_ts"))
    user = _coerce_str(event.get("user"))
    thread_root_text = (
        _coerce_str(event.get("thread_root_text"))
        or _coerce_str(event.get("parent_text"))
        or _coerce_str(raw_payload.get("thread_root_text"))
    )
    is_bot = bool(event.get("bot_id")) or str(event.get("subtype", "")).casefold() == "bot_message"

    raw_event_id = _coerce_str(raw_payload.get("event_id")) or _coerce_str(event.get("client_msg_id"))
    if raw_event_id:
        event_id = raw_event_id
    else:
        synthetic = f"{channel or ''}|{thread_ts or ''}|{ts or ''}|{user or ''}|{text}"
        event_id = "synthetic-" + hashlib.sha1(synthetic.encode("utf-8")).hexdigest()

    return ApprovalEvent(
        event_id=event_id,
        text=text,
        channel=channel,
        ts=ts,
        thread_ts=thread_ts,
        user=user,
        thread_root_text=thread_root_text,
        is_bot_message=is_bot,
    )


def load_cursor(path: str) -> dict[str, Any]:
    if not os.path.exists(path):
        return {"version": 1, "processed": {}}
    with open(path, "r", encoding="utf-8") as fh:
        payload = json.load(fh)
    if not isinstance(payload, dict):
        return {"version": 1, "processed": {}}
    processed = payload.get("processed")
    if not isinstance(processed, dict):
        payload["processed"] = {}
    return payload


def save_cursor(path: str, payload: dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2, sort_keys=True)


def prune_cursor(payload: dict[str, Any], max_entries: int = 2000) -> None:
    processed = payload.get("processed", {})
    if not isinstance(processed, dict):
        payload["processed"] = {}
        return
    if len(processed) <= max_entries:
        return
    sorted_items = sorted(processed.items(), key=lambda kv: str(kv[1]), reverse=True)[:max_entries]
    payload["processed"] = dict(sorted_items)


def resolve_run_id(text: str, thread_root_text: str | None, explicit_run_id: str | None) -> str | None:
    if explicit_run_id:
        return explicit_run_id.strip("`*_.,;:()[]{}")
    text_match = RUN_ID_RE.search(text or "")
    if text_match:
        return text_match.group(0).strip("`*_.,;:()[]{}")
    if thread_root_text:
        root_match = RUN_ID_RE.search(thread_root_text)
        if root_match:
            return root_match.group(0).strip("`*_.,;:()[]{}")
    return None


def _norm(text: str) -> str:
    return "".join(ch for ch in text.casefold() if ch.isalnum() or ch.isspace()).strip()


def extract_thread_titles(thread_root_text: str | None) -> list[str]:
    if not thread_root_text:
        return []
    titles: list[str] = []
    for line in thread_root_text.splitlines():
        match = re.match(r"^\s*\d+\.\s+(.+?)\s*$", line)
        if match:
            title = match.group(1).strip()
            if title:
                titles.append(title)
    return titles


def select_run_with_thread_hint(payload: dict[str, Any], thread_root_text: str | None) -> dict[str, Any] | None:
    hint_titles = [_norm(t) for t in extract_thread_titles(thread_root_text)]
    hint_titles = [t for t in hint_titles if t]
    if not hint_titles:
        return None

    runs = payload.get("runs", [])
    if not isinstance(runs, list):
        return None

    best_run: dict[str, Any] | None = None
    best_score = 0
    for run in runs:
        if not isinstance(run, dict):
            continue
        if run.get("status") not in {"pending_review", "pending", "partially_resolved"}:
            continue
        suggestions = run.get("suggestions", [])
        if not isinstance(suggestions, list):
            continue
        run_titles: list[str] = []
        for entry in suggestions:
            if not isinstance(entry, dict):
                continue
            task = entry.get("task", {})
            if not isinstance(task, dict):
                continue
            title = task.get("title")
            if isinstance(title, str) and title.strip():
                run_titles.append(_norm(title))
        if not run_titles:
            continue
        score = sum(1 for hint in hint_titles if any(hint in rt or rt in hint for rt in run_titles))
        if score > best_score:
            best_score = score
            best_run = run

    if best_score > 0:
        return best_run
    return None


def pending_count(run: dict[str, Any]) -> int:
    suggestions = run.get("suggestions", [])
    if not isinstance(suggestions, list):
        return 0
    return len([entry for entry in suggestions if isinstance(entry, dict) and entry.get("status") == "pending"])


def is_approval_prompt_thread(thread_root_text: str | None) -> bool:
    if not thread_root_text:
        return False
    return bool(APPROVAL_PROMPT_RE.search(thread_root_text))


def is_thread_decision_candidate(event: ApprovalEvent) -> bool:
    if event.is_bot_message:
        return False
    if not event.text:
        return False
    has_thread = bool(event.thread_ts and event.ts and event.thread_ts != event.ts)
    has_run = bool(RUN_ID_RE.search(event.text)) or bool(RUN_ID_RE.search(event.thread_root_text or ""))
    if has_run:
        return True
    if has_thread and is_approval_prompt_thread(event.thread_root_text):
        return True
    return False


def process_approval_event(args: argparse.Namespace, raw_payload: dict[str, Any]) -> ListenerResult:
    event = normalize_event(raw_payload)
    if not is_thread_decision_candidate(event):
        return ListenerResult(status="ignored", reason="not a thread decision candidate")

    cursor = load_cursor(args.cursor_file)
    processed = cursor.get("processed", {})
    if not isinstance(processed, dict):
        processed = {}
        cursor["processed"] = processed
    if event.event_id in processed:
        return ListenerResult(status="duplicate", reason="already processed event")

    try:
        decision = parse_decision_text(event.text)
    except SystemExit as exc:
        return ListenerResult(status="ignored", reason=str(exc))

    payload = load_pending_suggestions(args.pending_suggestions_file)
    run_id = resolve_run_id(event.text, event.thread_root_text, args.run_id or decision.run_id)
    if run_id:
        decision.run_id = run_id
    try:
        if run_id:
            run = select_run(payload, run_id)
        else:
            hinted = select_run_with_thread_hint(payload, event.thread_root_text)
            is_thread_reply = bool(event.thread_ts and event.ts and event.thread_ts != event.ts)
            if is_thread_reply:
                if hinted is None:
                    return ListenerResult(
                        status="ignored",
                        reason="thread reply did not match any pending approval prompt",
                    )
                run = hinted
            else:
                run = hinted if hinted is not None else select_run(payload, None)
    except SystemExit as exc:
        return ListenerResult(status="error", reason=str(exc))

    approved, rejected = apply_decision(run, decision)
    if not approved and not rejected:
        processed[event.event_id] = "noop"
        prune_cursor(cursor)
        save_cursor(args.cursor_file, cursor)
        save_pending_suggestions(args.pending_suggestions_file, payload)
        return ListenerResult(
            status="ignored",
            reason="no pending suggestions matched decision",
            run_id=str(run.get("run_id") or ""),
            pending_remaining=pending_count(run),
        )

    created = 0
    updated = 0
    skipped = 0
    if decision.action == "approve" and approved and not args.dry_run:
        tasks = [task_from_entry(entry) for entry in approved]
        sync = sync_tasks(args=args, tasks=tasks, emit_output=False)
        created = sync.created
        updated = sync.updated
        skipped = sync.skipped

    pending_remaining = pending_count(run)
    confirmation_message = build_confirmation_message(
        run_id=str(run.get("run_id") or ""),
        decision=decision,
        approved=approved,
        rejected=rejected,
        created=created,
        updated=updated,
        skipped=skipped,
        pending_remaining=pending_remaining,
        dry_run=args.dry_run,
    )

    save_pending_suggestions(args.pending_suggestions_file, payload)
    processed[event.event_id] = "processed"
    prune_cursor(cursor)
    save_cursor(args.cursor_file, cursor)

    if args.confirmation_message_file:
        directory = os.path.dirname(args.confirmation_message_file)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(args.confirmation_message_file, "w", encoding="utf-8") as fh:
            fh.write(confirmation_message)

    return ListenerResult(
        status="processed",
        reason="decision applied",
        run_id=str(run.get("run_id") or ""),
        approved_count=len(approved),
        rejected_count=len(rejected),
        created=created,
        updated=updated,
        skipped=skipped,
        pending_remaining=pending_remaining,
        confirmation_message=confirmation_message,
    )


def result_to_dict(result: ListenerResult) -> dict[str, Any]:
    return dataclasses.asdict(result)


def main() -> None:
    args = parse_args()
    raw_payload = read_event_payload(args)
    result = process_approval_event(args, raw_payload)
    payload = result_to_dict(result)
    print(json.dumps(payload, ensure_ascii=False))
    if args.result_file:
        directory = os.path.dirname(args.result_file)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(args.result_file, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, indent=2, sort_keys=True)


if __name__ == "__main__":
    main()
